### ISSUE TITLE
[bug] power event is always show 0

### ISSUE THREAD

**Issue by EG-easy** [cosmos-gaminghub/explorer-backend#75]
Each validator's voting event amount is always 0.

https://game-pre.game-explorer.io/validators/gamevaloper1pqanlf776tjtj6l3ftsd5s87rr29ddsf3jk8kn

<img width="803" alt="Screenshot 2022-02-15 143924" src="https://user-images.githubusercontent.com/35296935/153999591-ee5889e5-403a-4a0b-b5a1-962c35d92b69.png">

**Comment by padi-dev-hoangpa** [comment]
Explorer graphql
https://github.com/cosmos-gaminghub/explorer-graphql/pull/89
