### ISSUE TITLE
[improvement] show delegators info

### ISSUE THREAD

**Issue by EG-easy** [cosmos-gaminghub/explorer-backend#76]
It seems mintscan now shows delegators info.
It would be great if we can add this feature.

**Comment by padi-dev-hoangpa** [comment]
Explorer Graphql
https://github.com/cosmos-gaminghub/explorer-graphql/pull/88

**Comment by padi-dev-hoangpa** [comment]
- [ ] Feature api get delegators
- [ ] Feature frontend implement api get delegators

**Comment by padi-dev-hoangpa** [comment]
Explorer Graphql
https://github.com/cosmos-gaminghub/explorer-graphql/pull/88
